version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:1.6.15
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"  # MQTT port
      - "9001:9001"  # MQTT WebSockets port
    environment:
      - MQTT_USER=test
      - MQTT_PASSWORD=test
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - my_iot

  golang-web:
    build:
      dockerfile: ./docker/Dockerfile
    container_name: golang-web
    restart: always
    environment:
      - MQTT_USER=test
      - MQTT_PASSWORD=test
      - MQTT_ENDPOINT=tcp://mosquitto:1883
      - TOKEN_USERS=test:123123123
    ports:
      - "8081:8081"
    depends_on:
      - mosquitto
    networks:
      - my_iot

networks:
  my_iot: